version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10