// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    service_name,
    price,
    user_id,
    start_date,
    end_date
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      uuid.UUID   `json:"user_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalCost = `-- name: GetTotalCost :one
SELECT COALESCE(SUM(price), 0)::integer AS total
FROM subscriptions
WHERE
    ($1::uuid      IS NULL OR user_id      = $1)
    AND
    ($2::text IS NULL OR service_name = $2)
    AND start_date <= $3::date
    AND (end_date IS NULL OR end_date >= $4::date)
`

type GetTotalCostParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName pgtype.Text `json:"service_name"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	PeriodStart pgtype.Date `json:"period_start"`
}

func (q *Queries) GetTotalCost(ctx context.Context, arg GetTotalCostParams) (int32, error) {
	row := q.db.QueryRow(ctx, getTotalCost,
		arg.UserID,
		arg.ServiceName,
		arg.PeriodEnd,
		arg.PeriodStart,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at FROM subscriptions
WHERE
    ($1::uuid      IS NULL OR user_id      = $1)
    AND
    ($2::text IS NULL OR service_name = $2)
ORDER BY created_at DESC
LIMIT  $4
OFFSET $3
`

type ListSubscriptionsParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName pgtype.Text `json:"service_name"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.ServiceName,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    service_name = $1,
    price        = $2,
    start_date   = $3,
    end_date     = $4,
    updated_at   = NOW()
WHERE id = $5
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
